### ISSUE TITLE
Unable to SSH from bastion to other Droplets

### ISSUE THREAD

**Issue by npearson72** [Zelgius/terraform-sample-digitalocean-architectures#5]
I'm using the private IP `ssh 192.168.32.5` and getting:

```
root@192.168.32.5: Permission denied (publickey).
```

I had to manually upload my private key before it worked.

Any ideas?

**Comment by MasonEgger** [comment]
Are you using `ssh-agent`? You'll need that to pass the private key on your local machine through to the bastion. Then you ssh using `ssh -A root@ip`

**Comment by npearson72** [comment]
Shouldn't you be out celebrating? 😆 

That did it! Thank you!

Happy New Year's! 🍾 🥳
